In [1]:
import numpy as np

In [3]:
np.array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

In [5]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.full((3, 3,), 6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [15]:
np.random.rand(3, 3)
np.random.randn(3, 3)

array([[ 0.6596702 ,  1.29237756,  2.05503269],
       [-1.76900196, -1.83472516, -1.03065618],
       [-0.69230574, -0.63836216,  0.44931076]])

In [16]:
np.random.randint(0, 10, size=(3, 3))

array([[8, 8, 2],
       [3, 6, 8],
       [9, 9, 9]])

In [18]:
arr = np.full((3, 3,), 5)
arr.shape

(3, 3)

In [19]:
arr.reshape(3, 3)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [20]:
arr.flatten()

array([5, 5, 5, 5, 5, 5, 5, 5, 5])

In [21]:
np.transpose(arr)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [23]:
np.concatenate(arr)

array([5, 5, 5, 5, 5, 5, 5, 5, 5])

In [27]:
arr1 = np.full((3, 3,), 5)
arr2 = np.full((3, 3,), 6)
np.hstack((arr1, arr2))

array([[5, 5, 5, 6, 6, 6],
       [5, 5, 5, 6, 6, 6],
       [5, 5, 5, 6, 6, 6]])

In [26]:
np.vstack((arr1, arr2))

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [31]:
np.add(arr1, arr2) 

array([[11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]])

In [33]:
np.subtract(arr1, arr2) 

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [34]:
np.multiply(arr1, arr2) 

array([[30, 30, 30],
       [30, 30, 30],
       [30, 30, 30]])

In [35]:
np.divide(arr2, arr1) 

array([[1.2, 1.2, 1.2],
       [1.2, 1.2, 1.2],
       [1.2, 1.2, 1.2]])

In [36]:
np.sqrt(arr1)

array([[2.23606798, 2.23606798, 2.23606798],
       [2.23606798, 2.23606798, 2.23606798],
       [2.23606798, 2.23606798, 2.23606798]])

In [37]:
np.exp(arr1)

array([[148.4131591, 148.4131591, 148.4131591],
       [148.4131591, 148.4131591, 148.4131591],
       [148.4131591, 148.4131591, 148.4131591]])

In [38]:
np.log(arr2)

array([[1.79175947, 1.79175947, 1.79175947],
       [1.79175947, 1.79175947, 1.79175947],
       [1.79175947, 1.79175947, 1.79175947]])

In [40]:
np.power(arr2, 2)

array([[36, 36, 36],
       [36, 36, 36],
       [36, 36, 36]], dtype=int32)

In [41]:
np.mean(arr1) 

5.0

In [43]:
np.median(arr1) 

5.0

In [44]:
np.std(arr1)

0.0

In [45]:
np.sum(arr1, axis = 0)

array([15, 15, 15])

In [46]:
np.sum(arr1, axis = 1)

array([15, 15, 15])

In [47]:
np.prod(arr1, axis = 1)

array([125, 125, 125])

In [48]:
np.prod(arr1, axis = 0)

array([125, 125, 125])

In [52]:
arr1[0]

array([5, 5, 5])

In [51]:
arr1[1:3]

array([[5, 5, 5],
       [5, 5, 5]])

In [50]:
arr1[:, 1]

array([5, 5, 5])

In [53]:
arr[arr > 5]

array([6, 6, 6, 6, 6, 6, 6, 6, 6])

In [55]:
arr[[0, 2], [1, 2]]

array([6, 6])

In [56]:
np.sort(arr1)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [57]:
np.argsort(arr)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [58]:
np.where(arr > 5)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [59]:
np.unique(arr)

array([6])

In [61]:
np.argmax(arr)

0

In [64]:
np.argmin(arr)

0

In [65]:
arr + 5

array([[11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]])

In [73]:
arr1 = np.array([[2, 3, 1], [4, 7, 2], [3, 6, 8]])
np.linalg.inv(arr1)

array([[ 3.38461538, -1.38461538, -0.07692308],
       [-2.        ,  1.        ,  0.        ],
       [ 0.23076923, -0.23076923,  0.15384615]])

In [74]:
np.linalg.det(arr1)

12.999999999999995

In [76]:
np.linalg.eig(arr1)

EigResult(eigenvalues=array([12.2826451 ,  0.23618944,  4.48116547]), eigenvectors=array([[-0.22468003, -0.84792654, -0.16876378],
       [-0.4891876 ,  0.52440042, -0.43448577],
       [-0.84274218, -0.07761948,  0.88472645]]))

In [78]:
np.linalg.norm(arr1)

13.856406460551018

In [80]:
np.linalg.solve(arr1,arr2)

array([[11.53846154, 11.53846154, 11.53846154],
       [-6.        , -6.        , -6.        ],
       [ 0.92307692,  0.92307692,  0.92307692]])

In [81]:
np.clip(arr, a_min=0, a_max=10)

array([[2, 3, 1],
       [4, 7, 2],
       [3, 6, 8]])

In [83]:
normalized = (arr - np.mean(arr)) / np.std(arr)
normalized

array([[-0.8660254 , -0.4330127 , -1.29903811],
       [ 0.        ,  1.29903811, -0.8660254 ],
       [-0.4330127 ,  0.8660254 ,  1.73205081]])

In [85]:
np.random.shuffle(arr)
arr

array([[4, 7, 2],
       [2, 3, 1],
       [3, 6, 8]])

In [86]:
np.save('data.npy', arr)